services:
  concert-postgres:
    image: postgres:15-alpine
    container_name: concert-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: concert_db
      POSTGRES_USER: concert_user
      POSTGRES_PASSWORD: concert_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U concert_user -d concert_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - concert_pg_data:/var/lib/postgresql/data

  concert-app:
    build: .
    container_name: concert-app
    depends_on:
      concert-postgres:
        condition: service_healthy
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: pg
      SPRING_DATASOURCE_URL: jdbc:postgresql://concert-postgres:5432/concert_db
      SPRING_DATASOURCE_USERNAME: concert_user
      SPRING_DATASOURCE_PASSWORD: concert_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  concert_pg_data: